# Generated by Django 4.1.2 on 2022-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbail', models.ImageField(upload_to='lists')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('songs', models.ManyToManyField(to='songs.song')),
            ],
        ),
    ]
