# Generated by Django 4.1.2 on 2022-10-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsong',
            name='user',
        ),
    ]
