# Generated by Django 4.1.2 on 2022-10-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_listsong_user'),
        ('users', '0002_alter_artist_managers_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lists',
            field=models.ManyToManyField(to='lists.listsong'),
        ),
    ]
